### ISSUE TITLE
Unknown authentication error

### ISSUE THREAD

**Issue by paulobezerr** [lovebing/react-native-baidu-map#155]
When Baidu starts I receive this error and I don't know how to continue.

```
 baidumapsdk: Authentication Error errorcode: -1 uid: -1 appid -1 msg: Current network is not available.
```

The error code is strange and the message is not clear.
Something that I missed?

@spelcaster

**Comment by spelcaster** [comment]
![baidu-api-key](https://user-images.githubusercontent.com/3278419/37555144-920d0536-29c1-11e8-8f93-43a06db354ac.png)

The authentication error in this case was due to the use of a wrong bag name. The following commands should be run from the react-native application folder:

```shell
# debug sha1
keytool -list -v -keystore ~/.android/debug.keystore -keypass android | grep -i sha1 

# release sha1 (change {custom_name}  to your keystore name
keytool -list -v -keystore android/app/{custom_name}.keystore | grep -i sha1

# bag name is the name of your package
cat android/app/src/main/AndroidManifest.xml | grep "package="   
```

Fill the baidu form with thi and you should be good to go.

**Comment by paulobezerr** [comment]
Great, thank you @spelcaster!
